### ISSUE TITLE
Do I need a backend server for this usage scenario?

### ISSUE THREAD

**Issue by mentiflectax** [maxogden/voxel-engine#125]
Sorry for a dumb question.

Let's say I want to create pages with a voxel.JS-rendered worlds in them. Let's say a person should be able
- to walk in that 3D world and
- when he or she does certain things (e. g. go through a portal), the browser should redirect to another page (another HTML page with another Voxel.JS world in it).

I don't need authentication at the moment.

Do I need a backend for implementing this? If yes, what would the back end do?

**Comment by daniel-gwilt** [comment]
Hi Dpisarenko,

I'm thinking yes, you would need a back-end.  The reason I think this is because you'll need a way to save the 3D world.  You'll also need to save the assets like textures, sounds and models.  When a player loads your game you'll need to load the assets.  Then you'll also want a way to save the game's state.  So if I build a house in your game I can "save" and then come back to that house.

I'd recommend you start building the game.  Just jump in and start learning things.  Good luck and have fun!  ;-)

Disclaimer:
I've never built a voxel game, only a couple 2D games on my free time.  Although, I've been a software engineer for 6+ years.

**Comment by mentiflectax** [comment]
Thanks!

**Comment by petterarvidsson** [comment]
@dpisarenko If you are looking for a back end server I think https://github.com/konstructs/server (of which I am one of the maintainers) might fulfil this role for your project. It manages real time updates of a persistent voxel world and handles players that can interact with it. It uses a stand alone client (https://github.com/konstructs/client), so it should be possible to build a client based on this project as well. If not, all parts of the project is open source, so you might be able to get some inspiration for your own project. You can read more about the game itself at: http://www.konstructs.org/
