### ISSUE TITLE
voxeljs.com is now parked by a domain squatter

### ISSUE THREAD

**Issue by WAUthethird** [maxogden/voxel-engine#139]
So it looks like the domain name hasn't been renewed, and as such, a domain squatter now owns it. Check for yourself: [voxeljs.com](http://voxeljs.com/)

So obviously, some negotiating with the present domain owner now needs to be done.

**Comment by harry-wood** [comment]
I guess this was fixed since you wrote that. I see the voxeljs.com website now.

But I do still see some domain squatter junk appearing in an iframe under the "add-ons" heading. It's iframing "requirebin.com".  I guess this was another website by @maxogden based on this other repo: https://github.com/maxogden/requirebin

**Comment by harry-wood** [comment]
Looks like someone has brought back requirebin.com too now so it's... better. But I don't think the "add-ons" section is supposed to look like that

<img width="462" alt="Screenshot 2021-09-20 at 16 46 58" src="https://user-images.githubusercontent.com/227525/134033000-67d904a0-a45a-4d1f-916c-f4de7c30c4de.png">
